### PR TITLE
Updated install instructions for 2.6 GA release

### PR DESCRIPTION
**Pull request by LindsayHill**
SLX modules now ship with GA Ansible (2.6), simplifying install/setup procedures. Updated README docs to reflect this.

@DilrajSK can you please review this?

### CODE REVIEW

**Review by DilrajSK — COMMENTED** [review]
@LindsayHill  Looks fine to me. I see that you have removed all the virtual environment setup instructions from the SLX guide and in the root Readme, instead of mentioning "under active development", we changed it to "shipped in 2.6".

**Comment by LindsayHill** [comment]
Correct - while users can still use the virtualenv route, they no longer need to. They don't need to clone our repo any more, they can just install GA Ansible. 

If you're happy with this change, can you Approve it - on the "Files Changed" tab, click "Review Changes"

You should now have reviewer access. We have restrictions on this repo that require at least one approval before changes can be merged.

**Review by DilrajSK — APPROVED** [review]

**Comment by DilrajSK** [comment]
Done

**Comment by DilrajSK** [comment]
@LindsayHill Approved and Merged

**Pull request merged**
